
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-3
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-HelpRequestFix","number":86,"title":"App.js merge conflicts fixed","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/86"},{"author":{"id":"U_kgDOBZIIbQ","is_bot":false,"login":"clin947","name":"Xingye Lin"},"headRefName":"Cindy-UCSBOrganizationPlaceholders","number":84,"title":"Cindy ucsb organization placeholders","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/84"}]
