
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-3
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"andrew"},"headRefName":"Andrew-MenuItemReviewCreateEdit","number":76,"title":"[Andrew] Add MenuItemReview Create & Edit","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/76"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"andrew"},"headRefName":"Andrew-MenuItemReviewTable","number":75,"title":"[Andrew] Add MenuItemReview Table","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/75"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"andrew"},"headRefName":"Andrew-MenuItemReviewForm","number":74,"title":"[Andrew] Add MenuItemReview Form and Tests","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/74"},{"author":{"id":"MDQ6VXNlcjU4NDkyMDc2","is_bot":false,"login":"ryan-he-8","name":"Ryan He"},"headRefName":"RecRequestFrontEnd-Fixtures","number":73,"title":"rh - added the recommendation request fixtures","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/73"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":"Edwin-Yee"},"headRefName":"Edwin-UpdateReadMe","number":72,"title":"Removed brief overview of starter code header","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/72"},{"author":{"id":"U_kgDOBZIIbQ","is_bot":false,"login":"clin947","name":"Xingye Lin"},"headRefName":"Cindy-UCSBOrganizationFixtures","number":69,"title":"ucsb organization fixtures","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/69"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"andrew"},"headRefName":"Andrew-MenuItemReviewFixtures","number":66,"title":"[Andrew] Create MenuItemReview Fixtures","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/66"}]
