
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-3
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjU4NDkyMDc2","is_bot":false,"login":"ryan-he-8","name":"Ryan He"},"headRefName":"RecRequestFrontEnd-DoneAppears","number":88,"title":"boolean value now appears in the table","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/88"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"andrew"},"headRefName":"Andrew-RestoreDeleted","number":87,"title":"[Andrew] Restore deleted files","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/87"}]
