
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-3
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"andrew"},"headRefName":"Andrew-MenuItemReview","number":63,"title":"[Andrew] Add MenuItemReview CRUD Operations","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/63"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":""},"headRefName":"Edwin-UCSBDiningCommonsMenuForm","number":62,"title":"Edwin - UCSBDiningCommonsMenu Form","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/62"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-HelpRequestTableComponent","number":60,"title":"Help request table component","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/60"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-HelpRequestForm","number":59,"title":"help request form","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/59"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-HelpRequestFixtures","number":58,"title":"help request fixtures","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/58"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-HelpRequestFileCopy","number":57,"title":"help request file copy","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/57"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":""},"headRefName":"Edwin-UCSBDiningCommonsMenuFixtures","number":56,"title":"Edwin - Added UCSBDiningCommonsMenu Fixtures","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/56"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":""},"headRefName":"Copied_DiningCommonsMenuItem_Files","number":55,"title":"Edwin - Copied UCSBDiningCommonsMenu Files from Team02","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/55"}]
