
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-3
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-3
pull_requests: [{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":""},"headRefName":"Edwin-UCSBDiningCommonsMenuAll","number":70,"title":"Edwin - UCSBDiningCommonsMenuAll (Includes Everything including: App, navbar, form, table, tests)","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/70"},{"author":{"id":"U_kgDOBZIIbQ","is_bot":false,"login":"clin947","name":"Xingye Lin"},"headRefName":"Cindy-UCSBOrganizationFixtures","number":69,"title":"ucsb organization fixtures","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/69"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-HelpRequestPH","number":67,"title":"Help request page setup","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/67"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"andrew"},"headRefName":"Andrew-MenuItemReviewFixtures","number":66,"title":"[Andrew] Create MenuItemReview Fixtures","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/66"},{"author":{"id":"U_kgDOBZIIbQ","is_bot":false,"login":"clin947","name":"Xingye Lin"},"headRefName":"Cindy-CopyUCSBOrganization","number":65,"title":"copy UCSBOrganization files","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/65"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"andrew"},"headRefName":"Andrew-MenuItemReview","number":63,"title":"[Andrew] Add MenuItemReview CRUD Operations","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-3/pull/63"}]
